var fullName;
var firstName;
var lastName;
var boolean;
boolean = true;
firstName = "nur";
lastName = "zaman";
fullName = "nur zaman";
console.log(firstName.concat(lastName));
console.log(fullName);
console.log(boolean);
console.log(fullName.split(" "));
console.log(fullName.split(""));
console.log("first name ".concat(firstName, " last name ").concat(lastName, " ").concat(boolean));
